### PR TITLE
Features / Require authentication

### LINKED ISSUE #23: Require authentification
According to the `real-time-forum` task description, all of the pages should require authentification. 

- [x] Make all pages private. Make server-side redirect with request page restoration (to redirect back after login)
	- or show a blurred title and description with a login popup

- [x] Handle frontend server-side requests. Our frontend works in ISR mode, so we have to ignore the authentification check for Next.js requests.

### PR DESCRIPTION
**Pull request by maximihajlov**
Will be rebased when #57 will be merged. Resolves #23.

This pull request adds a new **private mode**, which makes all the endpoints (except `/api/login` and `/api/signup`) require authentication. This mode is enabled by default, but can be disabled by setting environment variable `FORUM_IS_PRIVATE` to `false`. 

This mode might be removed after passing `real-time-forum`, because `social-network` is allowed to be public. 

This mode is getting activated in `main.go`, so tests still test all endpoints like they are public. There's also a new `private_mode_test` file that tests if private mode works as expected.

### CODE REVIEW

**Comment by maximihajlov** [comment]
I've rebased the branch onto main. It's ready for review.

**Comment by nattikim** [comment]
When logout you can still surf thru the pages

**Review by nattikim — CHANGES_REQUESTED** [review]
When logout you can still surf thru previously visited pages

Something with going to the homepage, it doesn't open sometimes (when logged in)

*dev mode

**Comment by nattikim** [comment]
Error 500 when go to users/..

*dev mode

**Review by nattikim — APPROVED** [review]
LGTM

**Pull request merged**
