### PR TITLE
Features / Chat frontend improvements

### PR DESCRIPTION
**Pull request by maximihajlov**
This pull request adds all the necessary features for the `real-time-forum`. 

- [x] User list. A new tab in chat section which shows list of all users. Users are sorted alphabetically, online first. 

https://github.com/merpw/forum/assets/43277901/7ce8225c-0bbe-4964-a839-f5f0d3999eef

- [x] Lazy loading. Messages are now loaded when you scroll with groups of 10. Throttle was used.

https://github.com/merpw/forum/assets/43277901/45fda91b-4bd4-4b0b-8b22-b3c5d93a5ed8

And a few more:

- [x] `/chat/u{id}` route. Now users don't have to create a chat to start writing the message. Instead, when they open chat for the first time, it's empty. They can start typing and send a message, and only then a new chat is being created. 

https://github.com/merpw/forum/assets/43277901/5584b257-f6bc-482e-83e1-7341f11a0cef

- [x] Date separators. The dates are now shown as a separators between days:

https://github.com/merpw/forum/assets/43277901/226bd934-97a7-4cc5-aebf-a728b4f8eebc

This pull request adds only functionality, the design is a subject of #74

### CODE REVIEW

**Comment by maximihajlov** [comment]
@bomanviktor, this pull request might affect your websocket implementation. The response data of `chat/create`  has changed a little.

The request remains the same:

```json
{
  "type": "post",
  "item": {
    "url": "/chat/create",
    "data": {
      "userId": 2
    }
  }
}
```

And the response used to be:

```json
{
  "type": "post",
  "item": {
    "url": "/chat/create",
    "data": 3
  }
}
```

Now we've added `userId` to the response data:

```json
{
  "type": "post",
  "item": {
    "url": "/chat/create",
    "data": {
      "chatId": 3,
      "userId": 2
    }
  }
}
```

This makes it much easier to see if the user’s chat page was updated. Without a userId, we would have to create another` /chat/3` request to fetch chat data and see which user’s chat page was updated.

https://github.com/merpw/forum/assets/43277901/e2db1ef7-e752-4a18-955e-26b7e7d9b534

**Comment by bomanviktor** [comment]
Thank you for the Websocket response updates!! @maximihajlov

**Comment by nattikim** [comment]
Update the branch please

**Review by nattikim — APPROVED** [review]
LGTM 👍🏻

**Comment by maximihajlov** [comment]
> LGTM 👍🏻

Deployed successfully🎉 Thanks for the review! 🙏

**Pull request merged**
