### PR TITLE
Features / Chat service

### LINKED ISSUE #53: Chat functionality
## Frontend part:

- [ ] Define most of the handlers and messages
- [ ] Implement dummy TypeScript backend for testing purposes

### Next.js frontend: @maximihajlov 
- [ ] Implement Redux storage to store all chats and messages
- [ ] Implement all the necessary components for chat rendering
- [ ] Implement communication with the backend using WebSocket connection and Redux middleware
- [ ] Improve chat section to add tabs and show all the users
- [ ] Improve `ChatPage` design

### Vanilla frontend: @bomanviktor 

- [ ] Write a plan to improve team communication (you can edit this comment)

## Backend part: @healingdrawing and @sagarishere
- [ ] Define a new database tables and fields
- [ ] Implement database functions and queries to get the necessary data
- [ ] Implement handlers, define them as functions and call them in the basic HTTP handlers
- [ ] Implement WebSocket `/api/ws` endpoint and handle connections
- [ ] Implement WebSocket handlers, handle real-time events (when new message, send info about it to the necessary user)

### PR DESCRIPTION
**Pull request by maximihajlov**
This pull request resolves #53 and adds a new microservice `backend/chat`. 

This service has a separate database and connects to the main service `backend/forum` via REST API.

To check if client's token is valid, `chat` creates an `/api/internal/check-session?token=<token>` request to the `forum` service. 

To instantly remove client from `chat` when user logs out, there's a new `/api/internal/revoked-sessions` endpoint implemented. This endpoint uses [Server-sent events](https://en.wikipedia.org/wiki/Server-sent_events) to stream revoked sessions in real time:

https://github.com/merpw/forum/assets/43277901/e00892e6-ae51-4d4b-aba8-8bc75bf01aa7

Here's a new scheme of the whole infrastructure:
image

**Attention!** Deployment has changed:

- The old `backend` image is not supported anymore. It was renamed to `backend-forum`, so 

- Docker compose file on production should be changed. Maybe I'll push it later

- We now have two databases with default names `forum.db` and `chat.db`. If one wants to keep using `database.db` for forum service, it can be done using custom `DB_FILE` env variable.

### CODE REVIEW

**Comment by maximihajlov** [comment]
The new chat service can be tested using our [Postman Workspace](https://www.postman.com/restless-zodiac-600487/workspace/merpw/collection/644a668eecf3ee4b1948d6d8) and the frontend in [`features/chat-frontend`](https://github.com/merpw/forum/tree/features/chat-frontend)

**Review by bomanviktor — APPROVED** [review]
Straight forward. Could add some simple comments on some of the types (such as hub).

**Comment by nattikim** [comment]
I don't have permission in Postman Workspace :(

**Comment by nattikim** [comment]
yes, you have to use Postman Desktop, it doesn't work in browser for me, even in fork

**Comment by maximihajlov** [comment]
> yes, you have to use Postman Desktop, it doesn't work in browser for me, even in fork

Yeah, it's a Postman web limitation :(

image

**Comment by nattikim** [comment]
please update the branch :3

**Comment by maximihajlov** [comment]
> please update the branch :3

Done 👍

**Comment by nattikim** [comment]
It is possible to create chat with yourself. 
All the data being stored (Ids, messages etc) however it's error 500 (no rows in result set) on /chat/_chatIdWithYourself_

What was the idea behind that? It is unclear if we are going to implement single user chats and why???

**Comment by maximihajlov** [comment]
> It is possible to create chat with yourself. All the data being stored (Ids, messages etc) however it's error 500 (no rows in result set) on /chat/_chatIdWithYourself_ endpoint
> 
> What was the idea behind that? It is unclear if we are going to implement single user chats and why???

The idea was to be able to create a group chat with only one user (or chat with yourself) like in Telegram and Discord. This is a cool feature which makes possible to use messenger as a storage for some text/files. However, this feature is not going to be implemented in `real-time-forum`, so it makes sense to disable it for now.

**Comment by maximihajlov** [comment]
I've added some restrictions to prevent users from creating chats with users that don't exist, multiple chats between two users and chats with yourself

**Comment by nattikim** [comment]
> This is a cool feature which makes possible to use messenger as a storage for some text/files.

Yes but not sure about implementation.. because the data (f.e. in Memberships) is being duplicated in this case

**Review by nattikim — APPROVED** [review]
LGTM ☀️

**Pull request merged**
