### PR TITLE
Features / Chat frontend

### PR DESCRIPTION
**Pull request by maximihajlov**
This pull requests adds a new Redux-based frontend for chats. It's not final, design and more features will be added in future pull requests.

Features that are already implemented:

- [x] Chat section. New section in layout with list of all user chats. Shown on all the pages, can be collapsed

image

image

- [x] Let's chat button on user page that opens/creates a chat with the specific user

- [x] User status (online/offline)

- [x] Chat page `/chat/{id}` with all messaging functionality
  
https://github.com/merpw/forum/assets/43277901/253cef61-4124-4c03-89c6-390c073f56d1

Features like list of users and lazy loading will be implemented in future pull requests to simplify review process.

### CODE REVIEW

**Review by nattikim — CHANGES_REQUESTED** [review]
something with chat list sorting.. 
here you can see fresh chats placed at the bottom and are sorted in ascending order:
Screenshot 2023-07-01 at 19 42 29

**Comment by maximihajlov** [comment]
> something with chat list sorting.. here you can see fresh chats placed at the bottom and are sorted in ascending order

Thanks for the comment. Looks like in #61 we did not add sorting for `chat/all` endpoint, so the initial chats were sorted by the chat creation date and not the last message. I've just added this sorting.

**Comment by nattikim** [comment]
on more thing..
on invalid chat endpoint (f.e. `/chat/0`) we have "No chat selected" message

Screenshot 2023-07-01 at 20 34 57

for negative chat id (f.e. `/chat/-1`) we're getting "loading..."   
    
 


Screenshot 2023-07-01 at 20 33 56

**Comment by maximihajlov** [comment]
> one more thing.. on invalid chat endpoint (f.e. `/chat/0`) we have "No chat selected" message

Thanks! Fixed in 4143676840f8529080f5542aefdc5ad1088c9b1f

**Comment by nattikim** [comment]
It's better to have date separator. Right now it looks like all the messages are from the same day when it's not..
Screenshot 2023-07-01 at 22 59 39

**Comment by maximihajlov** [comment]
> It's better to have date separator. 

Sure! As I said before, it's just a basic version of the frontend. This feature will be added in future pull requests (probably the `design` one).

**Review by nattikim — APPROVED** [review]
LGTM 🕵🏻‍♀️

**Comment by maximihajlov** [comment]
Ooops... Infinite loading in the chat section in on forum-ci, the same bug exists locally when running with `docker compose` and `npm run start`. 

image

**Pull request merged**
