### PR TITLE
Features / 93 add avatar and bio

### LINKED ISSUE #93: Add avatar and about me fields to the sign up form
Add two new fields to the registration form: `avatar` and `bio`

Uploading of the avatars is not a requirement, so in the initial implementation we will pre-define them. They will be served by the frontend. We will have 10 different avatars with filenames `0.jpg`, `1.jpg` ... `9.jpg`

### Backend

Both new fields are optional strings. To store them in the database a new migration should be implemented. This change is very similar to adding new signup fields in #14. The type of new fields in models will be `sql.NullString`. 

Backend should check if avatar exists during sign up (matches `0..9.jpg`).

`bio` should have the same length limit as the post descriptions. 

This fields should be added to `/api/me` response to be able to see them on the profile page. 

Both `avatar` and `bio` fields are public and should be added to the `/api/users/{id}` response.

The tests should be updated to keep the coverage high.

### Frontend

Frontend will serve avatars, they will be stored as files in the `public` directory. 

The design of choosing avatars will look something like this: 

Image

During the sign up user can choose one of the avatars and add it as a name (e.g. `0.jpg`) to the signup request. `About me` field is like a post description. 

The `bio` should be shown on `/me` and `/user/{id}`. Avatar component should be updated.

### PR DESCRIPTION
**Pull request by maximihajlov**
This pull request resolves #93 and adds several new fields to the sign-up form

### CODE REVIEW

**Review by bomanviktor — APPROVED** [review]
Tested this earlier today. LGTM!

**Comment by maximihajlov** [comment]
The design is going to be improved by @nattikim, that's why the pull request was marked as not ready for the review

**Review by nattikim — CHANGES_REQUESTED** [review]
The avatar is visible only to the owner. It should be visible to everyone

Screen Shot 2023-08-03 at 23 26 41
Screen Shot 2023-08-03 at 23 27 04

**Comment by maximihajlov** [comment]
> The avatar is visible only to the owner. It should be visible to everyone

Good catch, fea062c1e472e8cfd8210a0230644b4356e01c7a fixes this

**Review by nattikim — APPROVED** [review]
LGTM

**Comment by maximihajlov** [comment]
Deployed to [forum-ci.mer.pw](https://forum-ci.mer.pw) successfully. Good job everybody 👏

image

**Pull request merged**
