### PR TITLE
Features / Followers and Invitations

### LINKED ISSUE #94: Add followers and profile privacy modes
## Backend

- [x] Add public mode

A new integer field `privacy` should be added to the `users` column. It can be `0` if profile is public or `1` if it's private. All existing users should have `1` as a default value. 

This field should be added to `/api/me` endpoint as bool. 

A new `POST /api/me/privacy` endpoint should be implemented. It should toggle privacy mode (similar to likes). It should return current privacy ("true" or "false")

Handler `/user/{id}` should be updated to send full name, date of birth and gender if the profile is public. 

- [x] Add followers. 

A new table `followers` should be added to the main database. It should be similar to the table `memberships` in chat database and contain several fields: primary key `id`, foreign key `user_id`, foreign key `follower_id` and a timestamp. 

The `followStatus` field should be added to `/users/{id}`. It can have three states (0-not following, 1-following, 2-requested to follow)

A new `/users/{id}/follow` endpoint should be implemented. It should toggle following of the user (similar to likes). It should return the `followStatus` (0, 1 or 2).

> Only for public profiles for now, private profiles require invitations #95 

This issue does not include post privacy, so all posts of users will remain public (and will be available to anyone).  

## Frontend

The `/user/{id}` page should be updated to render on client side. Right now it's server-side rendered, but since the profiles can be private, server will not have access to private fields of users. SWR fallback should be used for mutating data on client side. Like we already do for comments: 

https://github.com/merpw/forum/blob/db646fc8044cd55b5f9f11aa9e06537395872da9/frontend/src/app/post/%5Bid%5D/Comments.tsx#L12-L24

Follow button should be implemented. There should be indication if the user is followed or not. There should be a confirmation popup if you want to unfollow the user.

### PR DESCRIPTION
**Pull request by FinnTune**
Resolves #94 and #95 

Adds all the necessary endpoints for followers and invitations. Contains both frontend and backend.

### CODE REVIEW

**Comment by maximihajlov** [comment]
As I understand, this PR adds both followers and invitations, so should resolve both #94 and #95. Should we close #102 in this case?

**Comment by maximihajlov** [comment]
Now we have everything in the same branch. This is going to be a single pull request to resolve #94 and #95.

Now there's a bug, the casing of new fields for `/api/followers/{id}` is different. It's `userId` on frontend and `user_id` on backend. 


We should decide which casing to use. We already use `snake_case` in users (`first_name`, `last_name`). Bug we use `camelCase` in `followStatus`. There's no naming convention for JSON, but it should be consistent for a specific project. 

Google uses `camelCase`, ~~Twitter~~ X uses `snake_case`. Which one do you prefer?

https://stackoverflow.com/questions/5543490/json-naming-convention-snake-case-camelcase-or-pascalcase

**Comment by maximihajlov** [comment]
We already use `snake_case` in `main`, so I renamed the new fields. I've also fixed a bug with `/api/invitations` returning `null` instead of `[]` if there's no invitations.

**Review by maximihajlov — CHANGES_REQUESTED** [review]
Looks like we need one more field for invitations. 

Right now we have only `associated_id` (id of the user to follow, group or event) and `user_id` (id of the user we send the request to.

We now return follower id in `associated_id`, but this may cause a problems when inviting user to a group. If `user1` invites `user2` to the `group3`, we'll fill `associated_id` with `3`, and `user_id` with `2`, but there would be no place for data about user1 (who invited to the group). 

I think it's better to have `from_user_id` and `to_user_id`, and don't send `associated_id` at all (for follow requests). We'll add it back later (it will be id if the event or the group)

**Comment by maximihajlov** [comment]
As it was my bad (invalid description in #95), I've fixed it by myself. Now it should work as expected!

**Review by bomanviktor — CHANGES_REQUESTED** [review]
If you request to follow a private account, and they later go public, the `Cancel request` button should probably change to `Followed`:

image


Probably should add `Public` label to the right, and a better UI element on the switch when switching between privacy 

The list of users you follow, and users that follow you is missing in `/api/me`:

image

**Comment by bomanviktor** [comment]
Also, I noticed the notification actually updated in real time. It would be great if you could add it to the follow button as well.

**Comment by maximihajlov** [comment]
I've also refactored backend a bit, nothing critical, just a few bad practices. 

- Using `db.Query` for single-row queries. I didn't know that before (that's why we used it in our old code), but there's [db.QueryRow](https://pkg.go.dev/database/sql#DB.QueryRow), which is much more effective for such queries.

- Using several queries instead of a single one. It's bad idea to call one DB function from another, because it executes several queries instead of a single one. In our case I've optimized `GetFollowStatus` to have only one query, which will select some data from both `followers` and `invitations` table. SQL is pretty powerful language, so you can even write if statements with it. It's more efficient that calling two independent queries. 

```sql
    SELECT CASE 
    WHEN (
       SELECT 1 FROM followers WHERE user_id = ? AND follower_id = ?) THEN 1
    ELSE (
        SELECT CASE 
        WHEN (
        	SELECT 1 FROM invitations WHERE from_user_id = ? AND to_user_id = ?) THEN 2
        ELSE 0
    	END
    )
    END 
    AS follow_status
```

- Bad names for db functions. It looks much better if you add a prefix (`Get`, `Add`, `Remove`, `Update`) to your db functions. Instead of `Follow`, one can use `AddFollower` etc. 

- Functions should be more universal. Try to make them independent of the call context. E.g. in `GetFollowStatus(meId, userId int)`, you used `meId` as an argument, even though this function can be called to see follow status between two independent users (none of which is logged in). `GetFollowStatus(followerId, userId int)` makes more sense to me :)

Everything else is great (especially the tests)! LGTM 👏

**Comment by maximihajlov** [comment]
> Also, I noticed the notification actually updated in real time. It would be great if you could add it to the follow button as well.

It's actually not real-time. It's implemented using HTTP polling called on each navigation and focusing of the window. And it's the same for the follow button (and user data). 

https://github.com/merpw/forum/assets/43277901/c2c76e82-d59a-4336-bfba-d815179efa97

It's also mutated when user clicks the `Follow/Unfollow` button.

**Comment by maximihajlov** [comment]
> If you request to follow a private account, and they later go public, the `Cancel request` button should probably change to `Followed`:

Sure. This should be implemented on backend (to auto-approve all invitations if user became public).

> The list of users you follow, and users that follow you is missing in /api/me

True 😢 Did not see this question. I've already mentioned in #99, that we should have `/api/me/followers` to define post audience, so we can implement it here too. 

The same for `/api/me/followed`, array of ids of users you follow

**Comment by maximihajlov** [comment]
> Probably should add Public label to the right, and a better UI element on the switch when switching between privacy

There's a `private` badge is the user's profile is private. But as I see it does not appear because there's no `privacy` field in the `/api/users/{id}` response.

**Comment by bomanviktor** [comment]
> I've also refactored backend a bit, nothing critical, just a few bad practices. 
> 
> - Using `db.Query` for single-row queries. I didn't know that before (that's why we used it in our old code), but there's [db.QueryRow](https://pkg.go.dev/database/sql#DB.QueryRow), which is much more effective for such queries.
> 
> - Using several queries instead of a single one. It's bad idea to call one DB function from another, because it executes several queries instead of a single one. In our case I've optimized `GetFollowStatus` to have only one query, which will select some data from both `followers` and `invitations` table. SQL is pretty powerful language, so you can even write if statements with it. It's more efficient that calling two independent queries. 
> 
> ```sql
>     SELECT CASE 
>     WHEN (
>        SELECT 1 FROM followers WHERE user_id = ? AND follower_id = ?) THEN 1
>     ELSE (
>         SELECT CASE 
>         WHEN (
>         	SELECT 1 FROM invitations WHERE from_user_id = ? AND to_user_id = ?) THEN 2
>         ELSE 0
>     	END
>     )
>     END 
>     AS follow_status
> ```
> 
> - Bad names for db functions. It looks much better if you add a prefix (`Get`, `Add`, `Remove`, `Update`) to your db functions. Instead of `Follow`, one can use `AddFollower` etc. 
> 
> - Functions should be more universal. Try to make them independent of the call context. E.g. in `GetFollowStatus(meId, userId int)`, you used `meId` as an argument, even though this function can be called to see follow status between two independent users (none of which is logged in). `GetFollowStatus(followerId, userId int)` makes more sense to me :)
> 
> Everything else is great (especially the tests)! LGTM 👏

Really awesome update of the GetFollowStatus! I did not know this

**Comment by maximihajlov** [comment]
I've added the `public` badge for public profiles. Now the badge look like this.

(backend is still broken as there's no `privacy` field in the response)

image

image

**Comment by maximihajlov** [comment]
I've also added two new tabs to `/me` page. One with `followers`  and one with `users you follow`. Here how it looks with dummy data:


https://github.com/merpw/forum/assets/43277901/01b13869-0064-4c6a-89ca-4d92c6b26550

The design will be improved by @nattikim

**Comment by bomanviktor** [comment]
Could we add `Followers count` next to `Your followers` and `Users you follow`. Also, do we have an endpoint for `Users you follow`?

**Comment by bomanviktor** [comment]
> I've also added two new tabs to `/me` page. One with `followers` and one with `users you follow`. Here how it looks with dummy data:
> bandicam.2023-08-08.20-19-22-876.mp4
> 
> The design will be improved by @nattikim

The design of the privacy switch as well? It needs improvement. A simple color switch on toggle would do, and have "Public" to the right to the switch would make sense. Or a confirmation popup that asks you if you are sure to change privacy.

**Comment by maximihajlov** [comment]
> Could we add `Followers count` next to `Your followers` and `Users you follow`

Maybe it's better to add it as a field to `/users/{id]` and `/me/` responses, so we can show them in the card of the user.

> Also, do we have an endpoint for `Users you follow`?

I did not change backend, there is still no endpoint for fetching your followers or users you follow. I create requests to `/api/me/followers` and `/api/me/followed` (now it's just 404)

> Also, maybe it's time we remove create post from your own profile? And make post creation more like my real-time-forum (you stay on the main page, the form just appears above all the other posts). Makes it look more like a social network, and less like a forum.

We have this button in both places (`/me` and main page), IMO it's ok to keep it. The name of the project is still `forum`, so making posts is still the core feature. Separate page for post creation looks good to me too. We have too much fields (title, content, description, categories), so this from will take the whole screen and there would be no profit from having it on the main page.

**Comment by maximihajlov** [comment]
> The design of the privacy switch as well? It needs improvement. 

@nattikim 👀

**Comment by maximihajlov** [comment]
> Another thing that could be added: ability to update bio. It could be in /me/bio and would just take your new bio in the request body, and if status code 200, you can update it client side.

Editing of the profile is not a requirement. If we implement it, it will be something like `/me/edit`, which will allow users to edit the whole profile. 

Anyways profile editing and other possible features are not a subject of this PR (Followers and Invitations)

**Comment by bomanviktor** [comment]
> I've added the `public` badge for public profiles. Now the badge look like this.
> 
> (backend is still broken as there's no `privacy` field in the response)
> 
> image
> 
> image

I don't think badge is necessary for public profiles. I just looked at instagram and it is only giving a hint on private profiles.

It should say something like this:
```
Private profile:
Please follow them to see their information and posts
``` 

Maybe add a lock symbol to the left of the message. We have a bunch of space to use in the private profiles!

**Comment by bomanviktor** [comment]
> > Could we add `Followers count` next to `Your followers` and `Users you follow`
> 
> Maybe it's better to add it as a field to `/users/{id]` and `/me/` responses, so we can show them in the card of the user.

Yes, but what about the `/me` response? Will it be unnecessary since we have `/me/followers`? Or we take that one, put it inside the me response?

**Comment by bomanviktor** [comment]
I think at least the `/me` and `/user/id` endpoints needs to be updated. Maybe add privacy to the `/user/id` endpoint

**Comment by maximihajlov** [comment]
There's no need to include array to `/me` response, because user might not open the tab with followers. It's better to have follower count as a field instead and fetch array of followers only when user opens the tab.

**Comment by bomanviktor** [comment]
As far as functionality, it is looking good. I added `followers_count` and `following_count`  to  `/api/me` and `/api/users/id`. I also added `/api/me/following` which will return the list of usersIds which you follow.

**Review by bomanviktor — APPROVED** [review]

**Comment by maximihajlov** [comment]
I've just added the frontend for `followers_count` and `following_count` inspired by #101. This might be improved later to be clickable (and show list of followers in modal).

New tabs with followers are also fixed and connected to the valid endpoint. Looks good to me.

image

**Comment by maximihajlov** [comment]
I've fixed the bug with no `privacy` field (and no privacy badge). I've also added a lock icon to the privacy badge and removed the unnecessary `public` badge. 

image

**Comment by maximihajlov** [comment]
And... some tests for the new fields. I think we're now ready to merge

**Comment by maximihajlov** [comment]
Deployed successfully to [forum-ci.mer.pw](https://forum-ci.mer.pw). Bra jobbat, allihopa👏

**Pull request merged**
