### PR TITLE
Features / Typing in progress

### PR DESCRIPTION
**Pull request by maximihajlov**
Adds `user is typing...` message to the chat page and chat section.

https://github.com/merpw/forum/assets/43277901/6002558c-354d-49bc-8117-17ca29305d31

Part of the [typing-in-progress](https://github.com/01-edu/public/tree/master/subjects/real-time-forum/typing-in-progress) task

### CODE REVIEW

**Review by nattikim — CHANGES_REQUESTED** [review]
Works beautifully ✨
Let's apply similar to other elements styles.

The font color should be "info", just like all the other system messages and the size shouldn't  be bigger than message font size.
It also would be cool to apply that gradient dot styles (like in start-dot, end-dot classes) on the dots 🤩

**Comment by maximihajlov** [comment]
> The font color should be "info"

Info looks bad in both places as there's no enough contrast with the background. 

> It also would be cool to apply that gradient dot styles

Gradient on such a small message will be really hard to see, and the contrast with the background won't be enough

I've changed the size of this message in the chat list and changed the color to the `primary` on the chat page. Let me know what you think

**Comment by nattikim** [comment]
Looks great! ✨
One thing is that the dots in the Chat list looks bit too active compare to message text because of its weight. System messages like this shouldn't overweight it. So would be nice to have the dots only in Info color to balance everything.

Screen Shot 2023-07-18 at 21 01 33
Screen Shot 2023-07-18 at 21 04 32

**Comment by maximihajlov** [comment]
> So would be nice to have the dots only in Info color or play with its opacity to balance everything.

The info color has a little different shade in my opinion, so I've changed the opacity. Now it looks like this:

https://github.com/merpw/forum/assets/43277901/a6b024e6-a7af-4d47-9e46-9cf12905ba2a

**Review by nattikim — APPROVED** [review]
Beautiful 😻
Approved 👍🏻

**Pull request merged**
