### PR TITLE
Features / 109 Add events

### LINKED ISSUE #109: Add events

### PR DESCRIPTION
**Pull request by maximihajlov**
This PR resolves #109. It adds events to the groups

https://github.com/merpw/forum/assets/43277901/a67e03bb-35fa-46c7-b532-266cfcb89aea

### CODE REVIEW

**Comment by maximihajlov** [comment]
## [Test deployment](https://maximihajlov-laughing-zebra-qp7q57wg4v5c65g9-80.app.github.dev)

**Comment by maximihajlov** [comment]
I've just added time to the event's card

image

**Review by bomanviktor — CHANGES_REQUESTED** [review]
Notification for events DOES exist apparently...

**Comment by bomanviktor** [comment]
Make the colors different on `I'M IN` and `I'M OUT`. Also switch positions of the buttons so it's consistent with the other invites:
Screenshot 2023-08-17 at 17 40 31
Screenshot 2023-08-17 at 17 44 26

**Comment by maximihajlov** [comment]
Are you sure that you have the latest version. Your buttons are different, mine are not CAPSED:

image

**Comment by maximihajlov** [comment]
I've changed `events` tab to be a separate page `/group/{id}/events`. So now when you click on the invitation or create a new event, you will be redirected to the `events` tab on the group page:


https://github.com/merpw/forum/assets/43277901/c71fd79a-e2db-4804-a9a2-1450346bba75

**Comment by maximihajlov** [comment]
Design improvements will be handled by #101

**Comment by bomanviktor** [comment]
I am unable to recreate the 500 error after restarting the front end after the latest commit.

**Comment by bomanviktor** [comment]
Here is a video on how I trigger the error:
https://github.com/merpw/forum/assets/72476579/bcd4794f-808f-4afe-9838-1bece05f9692

**Comment by maximihajlov** [comment]
> I am getting this error when I have responded to invites, am on the posts tab, leave the group, ask to join, accept the request with admin, and click anywhere on the page to re-render.

This error was caused by invalid `member_status` check, which caused invalid appearing of the post list.

image


It was just fixed in e386091

**Review by bomanviktor — APPROVED** [review]
Nice fix! LGTM!

**Review by FinnTune — APPROVED** [review]
LGTM

**Pull request merged**
